// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dirichletprocess.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// current_memory_usage
size_t current_memory_usage();
RcppExport SEXP _dirichletprocess_current_memory_usage() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(current_memory_usage());
    return rcpp_result_gen;
END_RCPP
}
// benchmark_cpp_components_impl
Rcpp::List benchmark_cpp_components_impl(const Rcpp::List& dpObj, const Rcpp::StringVector& components, int times);
RcppExport SEXP _dirichletprocess_benchmark_cpp_components_impl(SEXP dpObjSEXP, SEXP componentsSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dpObj(dpObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(benchmark_cpp_components_impl(dpObj, components, times));
    return rcpp_result_gen;
END_RCPP
}
// benchmark_cpp_components
Rcpp::List benchmark_cpp_components(const Rcpp::List& dpObj, const Rcpp::StringVector& components, int times);
RcppExport SEXP _dirichletprocess_benchmark_cpp_components(SEXP dpObjSEXP, SEXP componentsSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dpObj(dpObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(benchmark_cpp_components(dpObj, components, times));
    return rcpp_result_gen;
END_RCPP
}
// beta_prior_draw_cpp
Rcpp::List beta_prior_draw_cpp(const Rcpp::NumericVector& priorParams, double maxT, int n);
RcppExport SEXP _dirichletprocess_beta_prior_draw_cpp(SEXP priorParamsSEXP, SEXP maxTSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_prior_draw_cpp(priorParams, maxT, n));
    return rcpp_result_gen;
END_RCPP
}
// beta_likelihood_cpp
Rcpp::NumericVector beta_likelihood_cpp(const Rcpp::NumericVector& x, double mu, double nu, double maxT);
RcppExport SEXP _dirichletprocess_beta_likelihood_cpp(SEXP xSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP maxTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_likelihood_cpp(x, mu, nu, maxT));
    return rcpp_result_gen;
END_RCPP
}
// beta_prior_density_cpp
double beta_prior_density_cpp(double mu, double nu, const Rcpp::NumericVector& priorParams, double maxT);
RcppExport SEXP _dirichletprocess_beta_prior_density_cpp(SEXP muSEXP, SEXP nuSEXP, SEXP priorParamsSEXP, SEXP maxTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_prior_density_cpp(mu, nu, priorParams, maxT));
    return rcpp_result_gen;
END_RCPP
}
// beta_metropolis_hastings_cpp
Rcpp::List beta_metropolis_hastings_cpp(const Rcpp::NumericMatrix& x, double startMu, double startNu, const Rcpp::NumericVector& priorParams, double maxT, const Rcpp::NumericVector& mhStep, int noDraws);
RcppExport SEXP _dirichletprocess_beta_metropolis_hastings_cpp(SEXP xSEXP, SEXP startMuSEXP, SEXP startNuSEXP, SEXP priorParamsSEXP, SEXP maxTSEXP, SEXP mhStepSEXP, SEXP noDrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type startMu(startMuSEXP);
    Rcpp::traits::input_parameter< double >::type startNu(startNuSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mhStep(mhStepSEXP);
    Rcpp::traits::input_parameter< int >::type noDraws(noDrawsSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_metropolis_hastings_cpp(x, startMu, startNu, priorParams, maxT, mhStep, noDraws));
    return rcpp_result_gen;
END_RCPP
}
// beta_posterior_draw_cpp
Rcpp::List beta_posterior_draw_cpp(const Rcpp::NumericVector& priorParams, double maxT_val, const Rcpp::NumericVector& mhStepSize_val, const Rcpp::NumericMatrix& x_data, int n_draws, int mhDrawsVal);
RcppExport SEXP _dirichletprocess_beta_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP maxT_valSEXP, SEXP mhStepSize_valSEXP, SEXP x_dataSEXP, SEXP n_drawsSEXP, SEXP mhDrawsValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mhStepSize_val(mhStepSize_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    Rcpp::traits::input_parameter< int >::type mhDrawsVal(mhDrawsValSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_posterior_draw_cpp(priorParams, maxT_val, mhStepSize_val, x_data, n_draws, mhDrawsVal));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_beta_cluster_parameter_update_cpp
SEXP nonconjugate_beta_cluster_parameter_update_cpp(Rcpp::List dp_list);
RcppExport SEXP _dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp(SEXP dp_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dp_list(dp_listSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_beta_cluster_parameter_update_cpp(dp_list));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_beta_cluster_component_update_cpp
SEXP nonconjugate_beta_cluster_component_update_cpp(Rcpp::List dp_list);
RcppExport SEXP _dirichletprocess_nonconjugate_beta_cluster_component_update_cpp(SEXP dp_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dp_list(dp_listSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_beta_cluster_component_update_cpp(dp_list));
    return rcpp_result_gen;
END_RCPP
}
// exponential_prior_draw_cpp
Rcpp::List exponential_prior_draw_cpp(Rcpp::NumericVector priorParams, int n);
RcppExport SEXP _dirichletprocess_exponential_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// exponential_posterior_draw_cpp
Rcpp::List exponential_posterior_draw_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x, int n);
RcppExport SEXP _dirichletprocess_exponential_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_posterior_draw_cpp(priorParams, x, n));
    return rcpp_result_gen;
END_RCPP
}
// exponential_posterior_parameters_cpp
Rcpp::NumericMatrix exponential_posterior_parameters_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x);
RcppExport SEXP _dirichletprocess_exponential_posterior_parameters_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_posterior_parameters_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// exponential_likelihood_cpp
Rcpp::NumericVector exponential_likelihood_cpp(Rcpp::NumericVector x, double lambda);
RcppExport SEXP _dirichletprocess_exponential_likelihood_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_likelihood_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// exponential_predictive_cpp
Rcpp::NumericVector exponential_predictive_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericVector x);
RcppExport SEXP _dirichletprocess_exponential_predictive_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_predictive_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_exponential_cluster_component_update_cpp
Rcpp::List conjugate_exponential_cluster_component_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_exponential_cluster_component_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_exponential_cluster_component_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_exponential_update_alpha_cpp
double conjugate_exponential_update_alpha_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_exponential_update_alpha_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_exponential_update_alpha_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_exponential_cluster_parameter_update_cpp
Rcpp::List conjugate_exponential_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_exponential_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_exponential_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_fit_cpp
Rcpp::List hierarchical_beta_fit_cpp(Rcpp::List dpList, int iterations, bool updatePrior, bool progressBar);
RcppExport SEXP _dirichletprocess_hierarchical_beta_fit_cpp(SEXP dpListSEXP, SEXP iterationsSEXP, SEXP updatePriorSEXP, SEXP progressBarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type updatePrior(updatePriorSEXP);
    Rcpp::traits::input_parameter< bool >::type progressBar(progressBarSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_fit_cpp(dpList, iterations, updatePrior, progressBar));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_cluster_component_update_cpp
Rcpp::List hierarchical_beta_cluster_component_update_cpp(Rcpp::List dpList);
RcppExport SEXP _dirichletprocess_hierarchical_beta_cluster_component_update_cpp(SEXP dpListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_cluster_component_update_cpp(dpList));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_global_parameter_update_cpp
Rcpp::List hierarchical_beta_global_parameter_update_cpp(Rcpp::List dpList);
RcppExport SEXP _dirichletprocess_hierarchical_beta_global_parameter_update_cpp(SEXP dpListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_global_parameter_update_cpp(dpList));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_update_g0_cpp
Rcpp::List hierarchical_beta_update_g0_cpp(Rcpp::List dpList);
RcppExport SEXP _dirichletprocess_hierarchical_beta_update_g0_cpp(SEXP dpListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_update_g0_cpp(dpList));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_update_gamma_cpp
Rcpp::List hierarchical_beta_update_gamma_cpp(Rcpp::List dpList);
RcppExport SEXP _dirichletprocess_hierarchical_beta_update_gamma_cpp(SEXP dpListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_update_gamma_cpp(dpList));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_beta_mixing_create_cpp
Rcpp::List hierarchical_beta_mixing_create_cpp(int n, Rcpp::NumericVector priorParameters, Rcpp::NumericVector hyperPriorParameters, Rcpp::NumericVector alphaPrior, double maxT, Rcpp::NumericVector gammaPrior, Rcpp::NumericVector mhStepSize, int num_sticks);
RcppExport SEXP _dirichletprocess_hierarchical_beta_mixing_create_cpp(SEXP nSEXP, SEXP priorParametersSEXP, SEXP hyperPriorParametersSEXP, SEXP alphaPriorSEXP, SEXP maxTSEXP, SEXP gammaPriorSEXP, SEXP mhStepSizeSEXP, SEXP num_sticksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParameters(priorParametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hyperPriorParameters(hyperPriorParametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alphaPrior(alphaPriorSEXP);
    Rcpp::traits::input_parameter< double >::type maxT(maxTSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gammaPrior(gammaPriorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mhStepSize(mhStepSizeSEXP);
    Rcpp::traits::input_parameter< int >::type num_sticks(num_sticksSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_beta_mixing_create_cpp(n, priorParameters, hyperPriorParameters, alphaPrior, maxT, gammaPrior, mhStepSize, num_sticks));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_prior_draw_cpp
Rcpp::List mvnormal_prior_draw_cpp(Rcpp::List priorParams, int n);
RcppExport SEXP _dirichletprocess_mvnormal_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_posterior_draw_cpp
Rcpp::List mvnormal_posterior_draw_cpp(Rcpp::List priorParams, Rcpp::NumericMatrix x, int n);
RcppExport SEXP _dirichletprocess_mvnormal_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_posterior_draw_cpp(priorParams, x, n));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_posterior_parameters_cpp
Rcpp::List mvnormal_posterior_parameters_cpp(Rcpp::List priorParams, Rcpp::NumericMatrix x);
RcppExport SEXP _dirichletprocess_mvnormal_posterior_parameters_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_posterior_parameters_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_predictive_cpp
Rcpp::NumericVector mvnormal_predictive_cpp(Rcpp::List priorParams, Rcpp::NumericMatrix x);
RcppExport SEXP _dirichletprocess_mvnormal_predictive_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_predictive_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_likelihood_cpp
Rcpp::NumericVector mvnormal_likelihood_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector mu, Rcpp::NumericMatrix sigma);
RcppExport SEXP _dirichletprocess_mvnormal_likelihood_cpp(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_likelihood_cpp(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_mvnormal_cluster_component_update_cpp
Rcpp::List conjugate_mvnormal_cluster_component_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_mvnormal_cluster_component_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_mvnormal_cluster_component_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_mvnormal_cluster_parameter_update_cpp
Rcpp::List conjugate_mvnormal_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_mvnormal_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_mvnormal_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal2_prior_draw_cpp
Rcpp::List mvnormal2_prior_draw_cpp(Rcpp::List priorParams, int n);
RcppExport SEXP _dirichletprocess_mvnormal2_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal2_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal2_posterior_draw_cpp
Rcpp::List mvnormal2_posterior_draw_cpp(Rcpp::List priorParams, Rcpp::NumericMatrix x, int n);
RcppExport SEXP _dirichletprocess_mvnormal2_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal2_posterior_draw_cpp(priorParams, x, n));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal2_likelihood_cpp
Rcpp::NumericVector mvnormal2_likelihood_cpp(Rcpp::NumericVector x, Rcpp::List theta);
RcppExport SEXP _dirichletprocess_mvnormal2_likelihood_cpp(SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal2_likelihood_cpp(x, theta));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_mvnormal2_cluster_component_update_cpp
Rcpp::List nonconjugate_mvnormal2_cluster_component_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_nonconjugate_mvnormal2_cluster_component_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_mvnormal2_cluster_component_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_mvnormal2_cluster_parameter_update_cpp
Rcpp::List nonconjugate_mvnormal2_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_nonconjugate_mvnormal2_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_mvnormal2_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_mvnormal2_fit_cpp
Rcpp::List hierarchical_mvnormal2_fit_cpp(Rcpp::List dpList, int iterations, bool updatePrior, bool progressBar);
RcppExport SEXP _dirichletprocess_hierarchical_mvnormal2_fit_cpp(SEXP dpListSEXP, SEXP iterationsSEXP, SEXP updatePriorSEXP, SEXP progressBarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpList(dpListSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type updatePrior(updatePriorSEXP);
    Rcpp::traits::input_parameter< bool >::type progressBar(progressBarSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_mvnormal2_fit_cpp(dpList, iterations, updatePrior, progressBar));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_mvnormal2_mixing_create_cpp
Rcpp::List hierarchical_mvnormal2_mixing_create_cpp(int n, Rcpp::List priorParameters, Rcpp::NumericVector alphaPrior, Rcpp::NumericVector gammaPrior, int num_sticks);
RcppExport SEXP _dirichletprocess_hierarchical_mvnormal2_mixing_create_cpp(SEXP nSEXP, SEXP priorParametersSEXP, SEXP alphaPriorSEXP, SEXP gammaPriorSEXP, SEXP num_sticksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type priorParameters(priorParametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alphaPrior(alphaPriorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gammaPrior(gammaPriorSEXP);
    Rcpp::traits::input_parameter< int >::type num_sticks(num_sticksSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_mvnormal2_mixing_create_cpp(n, priorParameters, alphaPrior, gammaPrior, num_sticks));
    return rcpp_result_gen;
END_RCPP
}
// markov_dp_create_cpp
Rcpp::List markov_dp_create_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_markov_dp_create_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_dp_create_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// markov_dp_fit_cpp
Rcpp::List markov_dp_fit_cpp(Rcpp::List dpObj, int iterations, bool updatePrior, bool progressBar);
RcppExport SEXP _dirichletprocess_markov_dp_fit_cpp(SEXP dpObjSEXP, SEXP iterationsSEXP, SEXP updatePriorSEXP, SEXP progressBarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type updatePrior(updatePriorSEXP);
    Rcpp::traits::input_parameter< bool >::type progressBar(progressBarSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_dp_fit_cpp(dpObj, iterations, updatePrior, progressBar));
    return rcpp_result_gen;
END_RCPP
}
// markov_dp_update_states_cpp
Rcpp::List markov_dp_update_states_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_markov_dp_update_states_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_dp_update_states_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// markov_dp_update_alpha_beta_cpp
Rcpp::List markov_dp_update_alpha_beta_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_markov_dp_update_alpha_beta_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_dp_update_alpha_beta_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// markov_dp_param_update_cpp
Rcpp::List markov_dp_param_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_markov_dp_param_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_dp_param_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// get_memory_tracking
Rcpp::DataFrame get_memory_tracking();
RcppExport SEXP _dirichletprocess_get_memory_tracking() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_memory_tracking());
    return rcpp_result_gen;
END_RCPP
}
// clear_memory_tracking
void clear_memory_tracking();
RcppExport SEXP _dirichletprocess_clear_memory_tracking() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_memory_tracking();
    return R_NilValue;
END_RCPP
}
// normal_prior_draw_cpp
Rcpp::List normal_prior_draw_cpp(Rcpp::NumericVector priorParams, int n);
RcppExport SEXP _dirichletprocess_normal_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// normal_posterior_draw_cpp
Rcpp::List normal_posterior_draw_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x, int n);
RcppExport SEXP _dirichletprocess_normal_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_posterior_draw_cpp(priorParams, x, n));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_cluster_component_update_cpp
Rcpp::List conjugate_cluster_component_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_cluster_component_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_cluster_component_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_cluster_parameter_update_cpp
Rcpp::List conjugate_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// normal_posterior_parameters_cpp
Rcpp::NumericMatrix normal_posterior_parameters_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x);
RcppExport SEXP _dirichletprocess_normal_posterior_parameters_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_posterior_parameters_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// weibull_prior_draw_cpp
Rcpp::List weibull_prior_draw_cpp(const Rcpp::NumericVector& priorParams, int n);
RcppExport SEXP _dirichletprocess_weibull_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(weibull_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// weibull_likelihood_cpp
Rcpp::NumericVector weibull_likelihood_cpp(const Rcpp::NumericVector& x, double alpha, double lambda);
RcppExport SEXP _dirichletprocess_weibull_likelihood_cpp(SEXP xSEXP, SEXP alphaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(weibull_likelihood_cpp(x, alpha, lambda));
    return rcpp_result_gen;
END_RCPP
}
// weibull_prior_density_cpp
double weibull_prior_density_cpp(double alpha, const Rcpp::NumericVector& priorParams);
RcppExport SEXP _dirichletprocess_weibull_prior_density_cpp(SEXP alphaSEXP, SEXP priorParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    rcpp_result_gen = Rcpp::wrap(weibull_prior_density_cpp(alpha, priorParams));
    return rcpp_result_gen;
END_RCPP
}
// weibull_posterior_draw_cpp
Rcpp::List weibull_posterior_draw_cpp(const Rcpp::NumericVector& priorParams, const Rcpp::NumericVector& mhStepSize, const Rcpp::NumericMatrix& x, int n);
RcppExport SEXP _dirichletprocess_weibull_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP mhStepSizeSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mhStepSize(mhStepSizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(weibull_posterior_draw_cpp(priorParams, mhStepSize, x, n));
    return rcpp_result_gen;
END_RCPP
}
// weibull_prior_parameters_update_cpp
Rcpp::NumericMatrix weibull_prior_parameters_update_cpp(const Rcpp::NumericVector& priorParams, const Rcpp::NumericVector& hyperPriorParams, const Rcpp::List& clusterParameters, int n);
RcppExport SEXP _dirichletprocess_weibull_prior_parameters_update_cpp(SEXP priorParamsSEXP, SEXP hyperPriorParamsSEXP, SEXP clusterParametersSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type hyperPriorParams(hyperPriorParamsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type clusterParameters(clusterParametersSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(weibull_prior_parameters_update_cpp(priorParams, hyperPriorParams, clusterParameters, n));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_weibull_cluster_parameter_update_cpp
Rcpp::List nonconjugate_weibull_cluster_parameter_update_cpp(Rcpp::List dp_list);
RcppExport SEXP _dirichletprocess_nonconjugate_weibull_cluster_parameter_update_cpp(SEXP dp_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dp_list(dp_listSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_weibull_cluster_parameter_update_cpp(dp_list));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_weibull_cluster_component_update_cpp
Rcpp::List nonconjugate_weibull_cluster_component_update_cpp(Rcpp::List dp_list);
RcppExport SEXP _dirichletprocess_nonconjugate_weibull_cluster_component_update_cpp(SEXP dp_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dp_list(dp_listSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_weibull_cluster_component_update_cpp(dp_list));
    return rcpp_result_gen;
END_RCPP
}
// normal_likelihood_cpp
Rcpp::NumericVector normal_likelihood_cpp(const Rcpp::NumericVector& x, double mu, double sigma);
RcppExport SEXP _dirichletprocess_normal_likelihood_cpp(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_likelihood_cpp(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// likelihood_cpp
Rcpp::NumericVector likelihood_cpp(const Rcpp::List& mdObj, const Rcpp::NumericVector& x, const Rcpp::List& theta);
RcppExport SEXP _dirichletprocess_likelihood_cpp(SEXP mdObjSEXP, SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mdObj(mdObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood_cpp(mdObj, x, theta));
    return rcpp_result_gen;
END_RCPP
}
// likelihood_normal_cpp
Rcpp::NumericVector likelihood_normal_cpp(Rcpp::List mdObj, Rcpp::NumericVector x, Rcpp::List theta);
RcppExport SEXP _dirichletprocess_likelihood_normal_cpp(SEXP mdObjSEXP, SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mdObj(mdObjSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood_normal_cpp(mdObj, x, theta));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _dirichletprocess_run_mcmc_cpp(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_dirichletprocess_current_memory_usage", (DL_FUNC) &_dirichletprocess_current_memory_usage, 0},
    {"_dirichletprocess_benchmark_cpp_components_impl", (DL_FUNC) &_dirichletprocess_benchmark_cpp_components_impl, 3},
    {"_dirichletprocess_benchmark_cpp_components", (DL_FUNC) &_dirichletprocess_benchmark_cpp_components, 3},
    {"_dirichletprocess_beta_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_beta_prior_draw_cpp, 3},
    {"_dirichletprocess_beta_likelihood_cpp", (DL_FUNC) &_dirichletprocess_beta_likelihood_cpp, 4},
    {"_dirichletprocess_beta_prior_density_cpp", (DL_FUNC) &_dirichletprocess_beta_prior_density_cpp, 4},
    {"_dirichletprocess_beta_metropolis_hastings_cpp", (DL_FUNC) &_dirichletprocess_beta_metropolis_hastings_cpp, 7},
    {"_dirichletprocess_beta_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_beta_posterior_draw_cpp, 6},
    {"_dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_nonconjugate_beta_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_beta_cluster_component_update_cpp, 1},
    {"_dirichletprocess_exponential_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_exponential_prior_draw_cpp, 2},
    {"_dirichletprocess_exponential_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_exponential_posterior_draw_cpp, 3},
    {"_dirichletprocess_exponential_posterior_parameters_cpp", (DL_FUNC) &_dirichletprocess_exponential_posterior_parameters_cpp, 2},
    {"_dirichletprocess_exponential_likelihood_cpp", (DL_FUNC) &_dirichletprocess_exponential_likelihood_cpp, 2},
    {"_dirichletprocess_exponential_predictive_cpp", (DL_FUNC) &_dirichletprocess_exponential_predictive_cpp, 2},
    {"_dirichletprocess_conjugate_exponential_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_exponential_cluster_component_update_cpp, 1},
    {"_dirichletprocess_conjugate_exponential_update_alpha_cpp", (DL_FUNC) &_dirichletprocess_conjugate_exponential_update_alpha_cpp, 1},
    {"_dirichletprocess_conjugate_exponential_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_exponential_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_hierarchical_beta_fit_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_fit_cpp, 4},
    {"_dirichletprocess_hierarchical_beta_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_cluster_component_update_cpp, 1},
    {"_dirichletprocess_hierarchical_beta_global_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_global_parameter_update_cpp, 1},
    {"_dirichletprocess_hierarchical_beta_update_g0_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_update_g0_cpp, 1},
    {"_dirichletprocess_hierarchical_beta_update_gamma_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_update_gamma_cpp, 1},
    {"_dirichletprocess_hierarchical_beta_mixing_create_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_beta_mixing_create_cpp, 8},
    {"_dirichletprocess_mvnormal_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_prior_draw_cpp, 2},
    {"_dirichletprocess_mvnormal_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_posterior_draw_cpp, 3},
    {"_dirichletprocess_mvnormal_posterior_parameters_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_posterior_parameters_cpp, 2},
    {"_dirichletprocess_mvnormal_predictive_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_predictive_cpp, 2},
    {"_dirichletprocess_mvnormal_likelihood_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_likelihood_cpp, 3},
    {"_dirichletprocess_conjugate_mvnormal_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_mvnormal_cluster_component_update_cpp, 1},
    {"_dirichletprocess_conjugate_mvnormal_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_mvnormal_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_mvnormal2_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_mvnormal2_prior_draw_cpp, 2},
    {"_dirichletprocess_mvnormal2_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_mvnormal2_posterior_draw_cpp, 3},
    {"_dirichletprocess_mvnormal2_likelihood_cpp", (DL_FUNC) &_dirichletprocess_mvnormal2_likelihood_cpp, 2},
    {"_dirichletprocess_nonconjugate_mvnormal2_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_mvnormal2_cluster_component_update_cpp, 1},
    {"_dirichletprocess_nonconjugate_mvnormal2_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_mvnormal2_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_hierarchical_mvnormal2_fit_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_mvnormal2_fit_cpp, 4},
    {"_dirichletprocess_hierarchical_mvnormal2_mixing_create_cpp", (DL_FUNC) &_dirichletprocess_hierarchical_mvnormal2_mixing_create_cpp, 5},
    {"_dirichletprocess_markov_dp_create_cpp", (DL_FUNC) &_dirichletprocess_markov_dp_create_cpp, 1},
    {"_dirichletprocess_markov_dp_fit_cpp", (DL_FUNC) &_dirichletprocess_markov_dp_fit_cpp, 4},
    {"_dirichletprocess_markov_dp_update_states_cpp", (DL_FUNC) &_dirichletprocess_markov_dp_update_states_cpp, 1},
    {"_dirichletprocess_markov_dp_update_alpha_beta_cpp", (DL_FUNC) &_dirichletprocess_markov_dp_update_alpha_beta_cpp, 1},
    {"_dirichletprocess_markov_dp_param_update_cpp", (DL_FUNC) &_dirichletprocess_markov_dp_param_update_cpp, 1},
    {"_dirichletprocess_get_memory_tracking", (DL_FUNC) &_dirichletprocess_get_memory_tracking, 0},
    {"_dirichletprocess_clear_memory_tracking", (DL_FUNC) &_dirichletprocess_clear_memory_tracking, 0},
    {"_dirichletprocess_normal_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_normal_prior_draw_cpp, 2},
    {"_dirichletprocess_normal_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_normal_posterior_draw_cpp, 3},
    {"_dirichletprocess_conjugate_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_cluster_component_update_cpp, 1},
    {"_dirichletprocess_conjugate_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_normal_posterior_parameters_cpp", (DL_FUNC) &_dirichletprocess_normal_posterior_parameters_cpp, 2},
    {"_dirichletprocess_weibull_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_weibull_prior_draw_cpp, 2},
    {"_dirichletprocess_weibull_likelihood_cpp", (DL_FUNC) &_dirichletprocess_weibull_likelihood_cpp, 3},
    {"_dirichletprocess_weibull_prior_density_cpp", (DL_FUNC) &_dirichletprocess_weibull_prior_density_cpp, 2},
    {"_dirichletprocess_weibull_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_weibull_posterior_draw_cpp, 4},
    {"_dirichletprocess_weibull_prior_parameters_update_cpp", (DL_FUNC) &_dirichletprocess_weibull_prior_parameters_update_cpp, 4},
    {"_dirichletprocess_nonconjugate_weibull_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_weibull_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_nonconjugate_weibull_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_weibull_cluster_component_update_cpp, 1},
    {"_dirichletprocess_normal_likelihood_cpp", (DL_FUNC) &_dirichletprocess_normal_likelihood_cpp, 3},
    {"_dirichletprocess_likelihood_cpp", (DL_FUNC) &_dirichletprocess_likelihood_cpp, 3},
    {"_dirichletprocess_likelihood_normal_cpp", (DL_FUNC) &_dirichletprocess_likelihood_normal_cpp, 3},
    {"_dirichletprocess_run_mcmc_cpp", (DL_FUNC) &_dirichletprocess_run_mcmc_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dirichletprocess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
