// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dirichletprocess.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// current_memory_usage
size_t current_memory_usage();
RcppExport SEXP _dirichletprocess_current_memory_usage() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(current_memory_usage());
    return rcpp_result_gen;
END_RCPP
}
// benchmark_cpp_components_impl
Rcpp::List benchmark_cpp_components_impl(const Rcpp::List& dpObj, const Rcpp::StringVector& components, int times);
RcppExport SEXP _dirichletprocess_benchmark_cpp_components_impl(SEXP dpObjSEXP, SEXP componentsSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dpObj(dpObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(benchmark_cpp_components_impl(dpObj, components, times));
    return rcpp_result_gen;
END_RCPP
}
// benchmark_cpp_components
Rcpp::List benchmark_cpp_components(const Rcpp::List& dpObj, const Rcpp::StringVector& components, int times);
RcppExport SEXP _dirichletprocess_benchmark_cpp_components(SEXP dpObjSEXP, SEXP componentsSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dpObj(dpObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(benchmark_cpp_components(dpObj, components, times));
    return rcpp_result_gen;
END_RCPP
}
// beta_likelihood_cpp
Rcpp::NumericVector beta_likelihood_cpp(const Rcpp::NumericVector& x_data, double mu_val, double nu_val, double maxT_val);
RcppExport SEXP _dirichletprocess_beta_likelihood_cpp(SEXP x_dataSEXP, SEXP mu_valSEXP, SEXP nu_valSEXP, SEXP maxT_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type mu_val(mu_valSEXP);
    Rcpp::traits::input_parameter< double >::type nu_val(nu_valSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_likelihood_cpp(x_data, mu_val, nu_val, maxT_val));
    return rcpp_result_gen;
END_RCPP
}
// beta_prior_draw_cpp
Rcpp::List beta_prior_draw_cpp(const Rcpp::NumericVector& priorParams, double maxT_val, int n_draws);
RcppExport SEXP _dirichletprocess_beta_prior_draw_cpp(SEXP priorParamsSEXP, SEXP maxT_valSEXP, SEXP n_drawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_prior_draw_cpp(priorParams, maxT_val, n_draws));
    return rcpp_result_gen;
END_RCPP
}
// beta_posterior_draw_cpp
Rcpp::List beta_posterior_draw_cpp(const Rcpp::NumericVector& priorParams, double maxT_val, const Rcpp::NumericVector& mhStepSize_val, const Rcpp::NumericMatrix& x_data, int n_draws, int mhDrawsNum);
RcppExport SEXP _dirichletprocess_beta_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP maxT_valSEXP, SEXP mhStepSize_valSEXP, SEXP x_dataSEXP, SEXP n_drawsSEXP, SEXP mhDrawsNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mhStepSize_val(mhStepSize_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    Rcpp::traits::input_parameter< int >::type mhDrawsNum(mhDrawsNumSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_posterior_draw_cpp(priorParams, maxT_val, mhStepSize_val, x_data, n_draws, mhDrawsNum));
    return rcpp_result_gen;
END_RCPP
}
// beta_prior_density_cpp
double beta_prior_density_cpp(double mu_val, double nu_val, const Rcpp::NumericVector& priorParams, double maxT_val);
RcppExport SEXP _dirichletprocess_beta_prior_density_cpp(SEXP mu_valSEXP, SEXP nu_valSEXP, SEXP priorParamsSEXP, SEXP maxT_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_val(mu_valSEXP);
    Rcpp::traits::input_parameter< double >::type nu_val(nu_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_prior_density_cpp(mu_val, nu_val, priorParams, maxT_val));
    return rcpp_result_gen;
END_RCPP
}
// nonconjugate_beta_cluster_parameter_update_cpp
Rcpp::List nonconjugate_beta_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(nonconjugate_beta_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// beta_metropolis_hastings_cpp
Rcpp::List beta_metropolis_hastings_cpp(const Rcpp::NumericMatrix& x_data, double startMu_val, double startNu_val, const Rcpp::NumericVector& priorParams, double maxT_val, const Rcpp::NumericVector& mhStepSize_val, int noDraws_val);
RcppExport SEXP _dirichletprocess_beta_metropolis_hastings_cpp(SEXP x_dataSEXP, SEXP startMu_valSEXP, SEXP startNu_valSEXP, SEXP priorParamsSEXP, SEXP maxT_valSEXP, SEXP mhStepSize_valSEXP, SEXP noDraws_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type startMu_val(startMu_valSEXP);
    Rcpp::traits::input_parameter< double >::type startNu_val(startNu_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< double >::type maxT_val(maxT_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mhStepSize_val(mhStepSize_valSEXP);
    Rcpp::traits::input_parameter< int >::type noDraws_val(noDraws_valSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_metropolis_hastings_cpp(x_data, startMu_val, startNu_val, priorParams, maxT_val, mhStepSize_val, noDraws_val));
    return rcpp_result_gen;
END_RCPP
}
// get_memory_tracking
Rcpp::DataFrame get_memory_tracking();
RcppExport SEXP _dirichletprocess_get_memory_tracking() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_memory_tracking());
    return rcpp_result_gen;
END_RCPP
}
// clear_memory_tracking
void clear_memory_tracking();
RcppExport SEXP _dirichletprocess_clear_memory_tracking() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_memory_tracking();
    return R_NilValue;
END_RCPP
}
// normal_prior_draw_cpp
Rcpp::List normal_prior_draw_cpp(Rcpp::NumericVector priorParams, int n);
RcppExport SEXP _dirichletprocess_normal_prior_draw_cpp(SEXP priorParamsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_prior_draw_cpp(priorParams, n));
    return rcpp_result_gen;
END_RCPP
}
// normal_posterior_draw_cpp
Rcpp::List normal_posterior_draw_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x, int n);
RcppExport SEXP _dirichletprocess_normal_posterior_draw_cpp(SEXP priorParamsSEXP, SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_posterior_draw_cpp(priorParams, x, n));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_cluster_component_update_cpp
Rcpp::List conjugate_cluster_component_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_cluster_component_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_cluster_component_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// conjugate_cluster_parameter_update_cpp
Rcpp::List conjugate_cluster_parameter_update_cpp(Rcpp::List dpObj);
RcppExport SEXP _dirichletprocess_conjugate_cluster_parameter_update_cpp(SEXP dpObjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dpObj(dpObjSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate_cluster_parameter_update_cpp(dpObj));
    return rcpp_result_gen;
END_RCPP
}
// normal_posterior_parameters_cpp
Rcpp::NumericMatrix normal_posterior_parameters_cpp(Rcpp::NumericVector priorParams, Rcpp::NumericMatrix x);
RcppExport SEXP _dirichletprocess_normal_posterior_parameters_cpp(SEXP priorParamsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorParams(priorParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_posterior_parameters_cpp(priorParams, x));
    return rcpp_result_gen;
END_RCPP
}
// normal_likelihood_cpp
Rcpp::NumericVector normal_likelihood_cpp(const Rcpp::NumericVector& x, double mu, double sigma);
RcppExport SEXP _dirichletprocess_normal_likelihood_cpp(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_likelihood_cpp(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// likelihood_cpp
Rcpp::NumericVector likelihood_cpp(const Rcpp::List& mdObj, const Rcpp::NumericVector& x, const Rcpp::List& theta);
RcppExport SEXP _dirichletprocess_likelihood_cpp(SEXP mdObjSEXP, SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mdObj(mdObjSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood_cpp(mdObj, x, theta));
    return rcpp_result_gen;
END_RCPP
}
// mvnormal_likelihood_cpp
arma::vec mvnormal_likelihood_cpp(const arma::mat& x, const arma::rowvec& mu, const arma::mat& sigma);
RcppExport SEXP _dirichletprocess_mvnormal_likelihood_cpp(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnormal_likelihood_cpp(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// likelihood_normal_cpp
Rcpp::NumericVector likelihood_normal_cpp(Rcpp::List mdObj, Rcpp::NumericVector x, Rcpp::List theta);
RcppExport SEXP _dirichletprocess_likelihood_normal_cpp(SEXP mdObjSEXP, SEXP xSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mdObj(mdObjSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood_normal_cpp(mdObj, x, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dirichletprocess_current_memory_usage", (DL_FUNC) &_dirichletprocess_current_memory_usage, 0},
    {"_dirichletprocess_benchmark_cpp_components_impl", (DL_FUNC) &_dirichletprocess_benchmark_cpp_components_impl, 3},
    {"_dirichletprocess_benchmark_cpp_components", (DL_FUNC) &_dirichletprocess_benchmark_cpp_components, 3},
    {"_dirichletprocess_beta_likelihood_cpp", (DL_FUNC) &_dirichletprocess_beta_likelihood_cpp, 4},
    {"_dirichletprocess_beta_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_beta_prior_draw_cpp, 3},
    {"_dirichletprocess_beta_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_beta_posterior_draw_cpp, 6},
    {"_dirichletprocess_beta_prior_density_cpp", (DL_FUNC) &_dirichletprocess_beta_prior_density_cpp, 4},
    {"_dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_beta_metropolis_hastings_cpp", (DL_FUNC) &_dirichletprocess_beta_metropolis_hastings_cpp, 7},
    {"_dirichletprocess_get_memory_tracking", (DL_FUNC) &_dirichletprocess_get_memory_tracking, 0},
    {"_dirichletprocess_clear_memory_tracking", (DL_FUNC) &_dirichletprocess_clear_memory_tracking, 0},
    {"_dirichletprocess_normal_prior_draw_cpp", (DL_FUNC) &_dirichletprocess_normal_prior_draw_cpp, 2},
    {"_dirichletprocess_normal_posterior_draw_cpp", (DL_FUNC) &_dirichletprocess_normal_posterior_draw_cpp, 3},
    {"_dirichletprocess_conjugate_cluster_component_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_cluster_component_update_cpp, 1},
    {"_dirichletprocess_conjugate_cluster_parameter_update_cpp", (DL_FUNC) &_dirichletprocess_conjugate_cluster_parameter_update_cpp, 1},
    {"_dirichletprocess_normal_posterior_parameters_cpp", (DL_FUNC) &_dirichletprocess_normal_posterior_parameters_cpp, 2},
    {"_dirichletprocess_normal_likelihood_cpp", (DL_FUNC) &_dirichletprocess_normal_likelihood_cpp, 3},
    {"_dirichletprocess_likelihood_cpp", (DL_FUNC) &_dirichletprocess_likelihood_cpp, 3},
    {"_dirichletprocess_mvnormal_likelihood_cpp", (DL_FUNC) &_dirichletprocess_mvnormal_likelihood_cpp, 3},
    {"_dirichletprocess_likelihood_normal_cpp", (DL_FUNC) &_dirichletprocess_likelihood_normal_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dirichletprocess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
