# Save as analysis/cpp_function_list_generator.R
create_cpp_function_list <- function() {
  output_filepath <- "analysis/code_documentation/cpp_functions_detailed.md"
  output_dir <- dirname(output_filepath)
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }

  sink(output_filepath)

  cat("# C++ Implementation Function List (Detailed)\n\n")
  cat("This document outlines the key C++ classes and functions planned for the reimplementation of `dirichletprocess` core components. Signatures use `arma` for matrices/vectors and `Rcpp::List` for complex R object interchange.\n\n")

  # --- Core Data Structures ---
  cat("## 1. Core Data Structures\n\n")
  cat("### 1.1. `MixingDistribution` (Abstract Base Class / Concept)\n")
  cat("Represents the component distribution $F(\\cdot | \\theta)$ and its prior $G_0$.\n")
  cat("```cpp\n")
  cat("class MixingDistribution {\n")
  cat("public:\n")
  cat("  virtual ~MixingDistribution() {}\n\n")
  cat("  // Calculate likelihood of data point(s) x given parameters theta\n")
  cat("  // x can be arma::vec for univariate, arma::mat for multivariate (rows are obs)\n")
  cat("  // theta is Rcpp::List {param1_name: arma::vec/mat, ...}\n")
  cat("  virtual arma::vec likelihood(const Rcpp::RObject& x_r, const Rcpp::List& theta) const = 0;\n\n")
  cat("  // Calculate log likelihood (often more stable)\n")
  cat("  virtual arma::vec log_likelihood(const Rcpp::RObject& x_r, const Rcpp::List& theta) const = 0;\n\n")
  cat("  // Draw n samples from the prior G0\n")
  cat("  // Returns Rcpp::List of parameter arrays {param1_name: arma::vec/mat, ...}\n")
  cat("  virtual Rcpp::List prior_draw(int n) const = 0;\n\n")
  cat("  // Draw n samples from the posterior p(theta | data_cluster, G0)\n")
  cat("  // data_cluster is arma::vec or arma::mat\n")
  cat("  virtual Rcpp::List posterior_draw(const Rcpp::RObject& data_cluster_r, int n_samples) const = 0;\n\n")
  cat("  // Calculate predictive likelihood for new data point(s) x_new (for conjugate models)\n")
  cat("  // Returns arma::vec of predictive likelihoods\n")
  cat("  virtual arma::vec predictive_likelihood(const Rcpp::RObject& x_new_r) const = 0;\n\n")
  cat("  // For non-conjugate models (used within MetropolisHastings)\n")
  cat("  // Calculate prior density p0(theta)\n")
  cat("  virtual double prior_density(const Rcpp::List& theta) const = 0; // log prior density often preferred\n\n")
  cat("  // Propose new parameters for Metropolis-Hastings\n")
  cat("  virtual Rcpp::List mh_parameter_proposal(const Rcpp::List& current_theta) const = 0;\n\n")
  cat("  // Store prior hyperparameters (e.g., as Rcpp::List or specific members)\n")
  cat("  Rcpp::List prior_parameters;\n")
  cat("  // Other model-specific fixed parameters (e.g., maxY for Beta, dimension for MVN)\n")
  cat("  // double maxY; // Example for Beta\n")
  cat("  // int dimension; // Example for MVN\n")
  cat("};\n")
  cat("```\n\n")

  cat("### 1.2. `DirichletProcess`\n")
  cat("Main object holding the DP state.\n")
  cat("```cpp\n")
  cat("class DirichletProcess {\n")
  cat("public:\n")
  cat("  // Data\n")
  cat("  arma::mat y_data;         // N x D data matrix (D=1 for univariate)\n")
  cat("  int n_obs;              // Number of observations\n")
  cat("  int data_dim;           // Dimension of data\n\n")
  cat("  // DP Parameters\n")
  cat("  double alpha;           // Concentration parameter\n")
  cat("  Rcpp::List alpha_prior_params; // Parameters for prior on alpha (e.g., shape, rate)\n\n")
  cat("  // Cluster Assignments & Counts\n")
  cat("  arma::uvec cluster_labels;   // Length N, assignments for each data point\n")
  cat("  arma::uvec points_per_cluster; // Length K, counts for each cluster\n")
  cat("  int num_clusters;         // Current number of active clusters K\n\n")
  cat("  // Cluster Parameters\n")
  cat("  // This will be a list of lists, where each inner list is a parameter set {name: value}\n")
  cat("  // e.g., params_for_cluster[k][\"mu\"], params_for_cluster[k][\"sigma_sq\"]\n")
  cat("  Rcpp::List cluster_parameters; // List of Rcpp::List, length K\n\n")
  cat("  // Mixing Distribution (polymorphic)\n")
  cat("  std::unique_ptr<MixingDistribution> mixing_dist;\n\n")
  cat("  // For non-conjugate models\n")
  cat("  int m_aux_params;         // Number of auxiliary parameters for Neal's Alg 8\n")
  cat("  int mh_draws;             // Number of MH draws for parameter updates\n\n")
  cat("  // For conjugate models (precomputed)\n")
  cat("  arma::vec predictive_array; // Stores predictive likelihood for each data point\n\n")
  cat("  // Constructor, methods, etc.\n")
  cat("  DirichletProcess(const Rcpp::List& r_dp_obj); // Constructor from R list\n")
  cat("  Rcpp::List to_R_list() const; // Convert back to R list\n\n")
  cat("  // Core MCMC update steps (will call C++ functions below)\n")
  cat("  void update_cluster_components();\n")
  cat("  void update_cluster_parameters();\n")
  cat("  void update_concentration_parameter();\n")
  cat("  void precompute_predictive_array_if_conjugate(); // For conjugate models\n")
  cat("};\n")
  cat("```\n\n")

  # --- Likelihood Functions ---
  cat("## 2. Likelihood Functions (as methods of specific MixingDistribution subclasses or standalone)\n\n")
  cat("These would ideally be methods of concrete `MixingDistribution` subclasses (e.g., `GaussianMixingDistribution : public MixingDistribution`).\n")
  cat("Signatures shown here are for conceptual C++ functions. Input `x_r` is `Rcpp::RObject` to handle `arma::vec` (univariate) or `arma::mat` (multivariate, rows as obs).\n`theta` is `Rcpp::List` like `Rcpp::List::create(Rcpp::Named(\"mu\")=mu_val, Rcpp::Named(\"sigma_sq\")=sigma_sq_val)`.\n\n")
  cat("```cpp\n")
  cat("// Gaussian: F(y | mu, sigma_sq)\n")
  cat("arma::vec likelihood_gaussian(const arma::vec& y, double mu, double sigma_sq);\n")
  cat("arma::vec log_likelihood_gaussian(const arma::vec& y, double mu, double sigma_sq);\n\n")
  cat("// Beta: F(y | mu_y, tau, maxY) (using mean/precision on [0, maxY])\n")
  cat("arma::vec likelihood_beta(const arma::vec& y, double mu_y, double tau, double maxY);\n")
  cat("arma::vec log_likelihood_beta(const arma::vec& y, double mu_y, double tau, double maxY);\n\n")
  cat("// Weibull: F(y | k_shape, lambda_scale)\n")
  cat("arma::vec likelihood_weibull(const arma::vec& y, double k_shape, double lambda_scale);\n")
  cat("arma::vec log_likelihood_weibull(const arma::vec& y, double k_shape, double lambda_scale);\n\n")
  cat("// Exponential: F(y | lambda_rate)\n")
  cat("arma::vec likelihood_exponential(const arma::vec& y, double lambda_rate);\n")
  cat("arma::vec log_likelihood_exponential(const arma::vec& y, double lambda_rate);\n\n")
  cat("// Multivariate Normal: F(y_vec | mu_vec, Sigma_mat)\n")
  cat("arma::vec likelihood_mvnormal(const arma::mat& y_mat, const arma::vec& mu_vec, const arma::mat& Sigma_mat);\n")
  cat("arma::vec log_likelihood_mvnormal(const arma::mat& y_mat, const arma::vec& mu_vec, const arma::mat& Sigma_mat);\n")
  cat("```\n\n")

  # --- Predictive Likelihood Functions ---
  cat("## 3. Predictive Likelihood Functions (for Conjugate Models)\n\n")
  cat("Calculate $\\int F(y_{new} | \\phi) dG_0(\\phi)$. `prior_params` from `MixingDistribution` object.\n\n")
  cat("```cpp\n")
  cat("// Gaussian (Normal-InvGamma G0)\n")
  cat("double predictive_gaussian(double y_new, const Rcpp::List& prior_params);\n\n")
  cat("// Exponential (Gamma G0)\n")
  cat("double predictive_exponential(double y_new, const Rcpp::List& prior_params);\n\n")
  cat("// Multivariate Normal (Normal-Wishart G0)\n")
  cat("double predictive_mvnormal(const arma::vec& y_new_vec, const Rcpp::List& prior_params, int dim);\n")
  cat("```\n\n")

  # --- Prior and Posterior Draw Functions ---
  cat("## 4. Prior and Posterior Draw Functions\n\n")
  cat("Return `Rcpp::List` of named parameters, e.g., `Rcpp::List::create(Rcpp::Named(\"mu\")=mu_draws, Rcpp::Named(\"sigma_sq\")=sigma_sq_draws)` where `mu_draws` is `arma::vec` of length `n_samples`.\n\n")
  cat("### 4.1. Prior Draw Functions ($G_0$)\n")
  cat("`prior_params` from `MixingDistribution` object.\n")
  cat("```cpp\n")
  cat("// Gaussian (Normal-InvGamma G0)\n")
  cat("Rcpp::List prior_draw_gaussian(const Rcpp::List& prior_params, int n_samples);\n\n")
  cat("// Beta (e.g., U for mu_y, Gamma for tau)\n")
  cat("Rcpp::List prior_draw_beta(const Rcpp::List& prior_params, double maxY, int n_samples);\n\n")
  cat("// Weibull (e.g., U for k, InvGamma for lambda)\n")
  cat("Rcpp::List prior_draw_weibull(const Rcpp::List& prior_params, int n_samples);\n\n")
  cat("// Exponential (Gamma G0 for rate)\n")
  cat("Rcpp::List prior_draw_exponential(const Rcpp::List& prior_params, int n_samples);\n\n")
  cat("// Multivariate Normal (Normal-Wishart G0)\n")
  cat("Rcpp::List prior_draw_mvnormal(const Rcpp::List& prior_params, int dim, int n_samples);\n")
  cat("```\n\n")

  cat("### 4.2. Posterior Draw Functions (Conjugate Models)\n")
  cat("`prior_params` from `MixingDistribution`, `data_cluster` is `arma::vec` or `arma::mat`.\n")
  cat("```cpp\n")
  cat("// Gaussian (Normal-InvGamma G0)\n")
  cat("Rcpp::List posterior_draw_gaussian(const arma::vec& data_cluster, const Rcpp::List& prior_params, int n_samples);\n\n")
  cat("// Exponential (Gamma G0)\n")
  cat("Rcpp::List posterior_draw_exponential(const arma::vec& data_cluster, const Rcpp::List& prior_params, int n_samples);\n\n")
  cat("// Multivariate Normal (Normal-Wishart G0)\n")
  cat("Rcpp::List posterior_draw_mvnormal(const arma::mat& data_cluster, const Rcpp::List& prior_params, int dim, int n_samples);\n")
  cat("```\n\n")

  # --- MCMC Core Algorithms ---
  cat("## 5. MCMC Core Algorithm Components\n\n")
  cat("These functions will likely take a C++ `DirichletProcess& dp_obj_cpp` by reference to modify it, or be methods of the `DirichletProcess` class.\nFor R interface, they might be wrapped to accept/return `Rcpp::List`.\n\n")
  cat("```cpp\n")
  cat("// Updates cluster assignments (Neal's Algorithm 3 for conjugate, 8 for non-conjugate)\n")
  cat("void cluster_component_update(DirichletProcess& dp_obj_cpp);\n")
  cat("// R-callable wrapper might look like:\n")
  cat("// Rcpp::List rcpp_cluster_component_update(Rcpp::List r_dp_obj);\n\n")

  cat("// Updates parameters for each cluster\n")
  cat("void cluster_parameter_update(DirichletProcess& dp_obj_cpp);\n")
  cat("// R-callable wrapper:\n")
  cat("// Rcpp::List rcpp_cluster_parameter_update(Rcpp::List r_dp_obj);\n\n")

  cat("// Updates concentration parameter alpha\n")
  cat("void update_alpha_parameter(DirichletProcess& dp_obj_cpp);\n")
  cat("// R-callable wrapper (or direct if simpler):\n")
  cat("// double rcpp_update_alpha(double current_alpha, int n_obs, int num_clusters, const arma::vec& alpha_prior_params);\n\n")

  cat("// Utility for ClusterComponentUpdate: manages changes to cluster labels, counts, params\n")
  cat("void cluster_label_change(DirichletProcess& dp_obj_cpp, \n")
  cat("                          int data_point_idx, \n")
  cat("                          int new_cluster_assignment_logical_idx, // 1 to K (existing) or K+1 to K+M (new/aux)\n")
  cat("                          int old_cluster_label, \n")
  cat("                          const Rcpp::List& params_for_new_cluster_if_any); // Parameters if new from aux or posterior draw\n\n")

  cat("// For non-conjugate ClusterParameterUpdate:\n")
  cat("Rcpp::List metropolis_hastings_sampler(\n")
  cat("    const MixingDistribution& mix_dist,         // To access likelihood, prior_density, mh_proposal\n")
  cat("    const Rcpp::RObject& data_cluster_r,        // Data for this cluster\n")
  cat("    const Rcpp::List& initial_params,           // Starting parameters for MH\n")
  cat("    int num_draws,                              // Number of MH iterations\n")
  cat("    const Rcpp::List& mh_proposal_control_params // e.g., step sizes\n")
  cat(");\n\n")

  cat("// Helper for MH: Propose new parameters (example for Beta, others needed)\n")
  cat("Rcpp::List mh_proposal_beta(const Rcpp::List& current_params, const Rcpp::List& control_params, double maxY);\n\n")

  cat("// Helper for MH: Calculate log prior density (example for Beta, others needed)\n")
  cat("double log_prior_density_beta(const Rcpp::List& params, const Rcpp::List& prior_hyperparams, double maxY);\n")
  cat("```\n\n")

  # --- Hierarchical Model Components (Future Scope, placeholder) ---
  cat("## 6. Hierarchical Model Components (Future Scope)\n\n")
  cat("```cpp\n")
  cat("// void global_parameter_update_hdp(HDPObject& hdp_obj);\n")
  cat("// void update_g0_hdp(HDPObject& hdp_obj);\n")
  cat("// void update_gamma_hdp(HDPObject& hdp_obj);\n")
  cat("```\n\n")

  # --- Rcpp Exported Functions (Wrappers) ---
  cat("## 7. Rcpp Exported Functions (Example Wrappers)\n\n")
  cat("These functions will be exposed to R and will typically convert R objects (Lists) to C++ objects, call the core C++ logic, and convert results back.\n\n")
  cat("```cpp\n")
  cat("// [[Rcpp::export]]\n")
  cat("Rcpp::List Fit_cpp(Rcpp::List r_dp_obj, int num_iterations, bool progress_bar) {\n")
  cat("  // 1. Convert r_dp_obj to C++ DirichletProcess object\n")
  cat("  // 2. Loop num_iterations:\n")
  cat("  //      call C++ update_cluster_components\n")
  cat("  //      call C++ update_cluster_parameters\n")
  cat("  //      call C++ update_alpha_parameter\n")
  cat("  // 3. Convert C++ DirichletProcess object back to Rcpp::List\n")
  cat("  // return updated_r_dp_obj;\n")
  cat("  return R_NilValue; // Placeholder\n")
  cat("}\n\n")
  cat("// Individual component wrappers if needed for direct R access/testing\n")
  cat("// [[Rcpp::export]]\n")
  cat("Rcpp::List ClusterComponentUpdate_cpp(Rcpp::List r_dp_obj) { /* ... */ return R_NilValue; }\n")
  cat("// [[Rcpp::export]]\n")
  cat("Rcpp::List ClusterParameterUpdate_cpp(Rcpp::List r_dp_obj) { /* ... */ return R_NilValue; }\n")
  cat("// [[Rcpp::export]]\n")
  cat("Rcpp::List UpdateAlpha_cpp(Rcpp::List r_dp_obj) { /* ... */ return R_NilValue; }\n")
  cat("```\n\n")

  sink()
  cat("C++ function list (detailed) generated at:", output_filepath, "\n")
}

# To run this script:
create_cpp_function_list()
cat("R script 'create_cpp_function_list' is defined.\nCall it to generate the Markdown file.\n")

