# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_likelihood_cpp <- function(x, mu, sigma) {
    .Call('_dirichletprocess_normal_likelihood_cpp', PACKAGE = 'dirichletprocess', x, mu, sigma)
}

likelihood_cpp <- function(mdObj, x, theta) {
    .Call('_dirichletprocess_likelihood_cpp', PACKAGE = 'dirichletprocess', mdObj, x, theta)
}

mvnormal_likelihood_cpp <- function(x, mu, sigma) {
    .Call('_dirichletprocess_mvnormal_likelihood_cpp', PACKAGE = 'dirichletprocess', x, mu, sigma)
}

likelihood_normal_cpp <- function(mdObj, x, theta) {
    .Call('_dirichletprocess_likelihood_normal_cpp', PACKAGE = 'dirichletprocess', mdObj, x, theta)
}

