# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

current_memory_usage <- function() {
    .Call(`_dirichletprocess_current_memory_usage`)
}

benchmark_cpp_components_impl <- function(dpObj, components, times) {
    .Call(`_dirichletprocess_benchmark_cpp_components_impl`, dpObj, components, times)
}

benchmark_cpp_components <- function(dpObj, components, times) {
    .Call(`_dirichletprocess_benchmark_cpp_components`, dpObj, components, times)
}

beta_prior_draw_cpp <- function(priorParams, maxT, n) {
    .Call(`_dirichletprocess_beta_prior_draw_cpp`, priorParams, maxT, n)
}

beta_likelihood_cpp <- function(x, mu, nu, maxT) {
    .Call(`_dirichletprocess_beta_likelihood_cpp`, x, mu, nu, maxT)
}

beta_prior_density_cpp <- function(mu, nu, priorParams, maxT) {
    .Call(`_dirichletprocess_beta_prior_density_cpp`, mu, nu, priorParams, maxT)
}

beta_metropolis_hastings_cpp <- function(x, startMu, startNu, priorParams, maxT, mhStep, noDraws) {
    .Call(`_dirichletprocess_beta_metropolis_hastings_cpp`, x, startMu, startNu, priorParams, maxT, mhStep, noDraws)
}

beta_posterior_draw_cpp <- function(priorParams, maxT_val, mhStepSize_val, x_data, n_draws, mhDrawsVal) {
    .Call(`_dirichletprocess_beta_posterior_draw_cpp`, priorParams, maxT_val, mhStepSize_val, x_data, n_draws, mhDrawsVal)
}

nonconjugate_beta_cluster_parameter_update_cpp <- function(dp_list) {
    .Call(`_dirichletprocess_nonconjugate_beta_cluster_parameter_update_cpp`, dp_list)
}

nonconjugate_beta_cluster_component_update_cpp <- function(dp_list) {
    .Call(`_dirichletprocess_nonconjugate_beta_cluster_component_update_cpp`, dp_list)
}

#' @title Draw from a Multivariate Normal-Wishart prior (C++)
NULL

#' @title Draw from a Multivariate Normal-Wishart posterior (C++)
NULL

#' @title Calculate MVNormal posterior parameters (C++)
NULL

#' @title Calculate MVNormal predictive distribution (C++)
NULL

#' @title Calculate MVNormal likelihood (C++)
NULL

#' @title Update cluster components for MVNormal (C++ conjugate)
NULL

#' @title Update cluster parameters for MVNormal (C++ conjugate)
NULL

mvnormal_prior_draw_cpp <- function(priorParams, n = 1L) {
    .Call(`_dirichletprocess_mvnormal_prior_draw_cpp`, priorParams, n)
}

mvnormal_posterior_draw_cpp <- function(priorParams, x, n = 1L) {
    .Call(`_dirichletprocess_mvnormal_posterior_draw_cpp`, priorParams, x, n)
}

mvnormal_posterior_parameters_cpp <- function(priorParams, x) {
    .Call(`_dirichletprocess_mvnormal_posterior_parameters_cpp`, priorParams, x)
}

mvnormal_predictive_cpp <- function(priorParams, x) {
    .Call(`_dirichletprocess_mvnormal_predictive_cpp`, priorParams, x)
}

mvnormal_likelihood_cpp <- function(x, mu, sigma) {
    .Call(`_dirichletprocess_mvnormal_likelihood_cpp`, x, mu, sigma)
}

conjugate_mvnormal_cluster_component_update_cpp <- function(dpObj) {
    .Call(`_dirichletprocess_conjugate_mvnormal_cluster_component_update_cpp`, dpObj)
}

conjugate_mvnormal_cluster_parameter_update_cpp <- function(dpObj) {
    .Call(`_dirichletprocess_conjugate_mvnormal_cluster_parameter_update_cpp`, dpObj)
}

get_memory_tracking <- function() {
    .Call(`_dirichletprocess_get_memory_tracking`)
}

clear_memory_tracking <- function() {
    invisible(.Call(`_dirichletprocess_clear_memory_tracking`))
}

#' @title Draw from a Normal distribution prior (C++)
NULL

#' @title Draw from a Normal distribution posterior (C++)
NULL

#' @title Update cluster components (C++ conjugate)
NULL

#' @title Update cluster parameters (C++ conjugate)
NULL

#' @title Calculate Normal posterior parameters (C++)
NULL

normal_prior_draw_cpp <- function(priorParams, n = 1L) {
    .Call(`_dirichletprocess_normal_prior_draw_cpp`, priorParams, n)
}

normal_posterior_draw_cpp <- function(priorParams, x, n = 1L) {
    .Call(`_dirichletprocess_normal_posterior_draw_cpp`, priorParams, x, n)
}

conjugate_cluster_component_update_cpp <- function(dpObj) {
    .Call(`_dirichletprocess_conjugate_cluster_component_update_cpp`, dpObj)
}

conjugate_cluster_parameter_update_cpp <- function(dpObj) {
    .Call(`_dirichletprocess_conjugate_cluster_parameter_update_cpp`, dpObj)
}

normal_posterior_parameters_cpp <- function(priorParams, x) {
    .Call(`_dirichletprocess_normal_posterior_parameters_cpp`, priorParams, x)
}

weibull_prior_draw_cpp <- function(priorParams, n = 1L) {
    .Call(`_dirichletprocess_weibull_prior_draw_cpp`, priorParams, n)
}

weibull_likelihood_cpp <- function(x, alpha, lambda) {
    .Call(`_dirichletprocess_weibull_likelihood_cpp`, x, alpha, lambda)
}

weibull_prior_density_cpp <- function(alpha, priorParams) {
    .Call(`_dirichletprocess_weibull_prior_density_cpp`, alpha, priorParams)
}

weibull_posterior_draw_cpp <- function(priorParams, mhStepSize, x, n = 1L) {
    .Call(`_dirichletprocess_weibull_posterior_draw_cpp`, priorParams, mhStepSize, x, n)
}

weibull_prior_parameters_update_cpp <- function(priorParams, hyperPriorParams, clusterParameters, n = 1L) {
    .Call(`_dirichletprocess_weibull_prior_parameters_update_cpp`, priorParams, hyperPriorParams, clusterParameters, n)
}

nonconjugate_weibull_cluster_parameter_update_cpp <- function(dp_list) {
    .Call(`_dirichletprocess_nonconjugate_weibull_cluster_parameter_update_cpp`, dp_list)
}

nonconjugate_weibull_cluster_component_update_cpp <- function(dp_list) {
    .Call(`_dirichletprocess_nonconjugate_weibull_cluster_component_update_cpp`, dp_list)
}

normal_likelihood_cpp <- function(x, mu, sigma) {
    .Call(`_dirichletprocess_normal_likelihood_cpp`, x, mu, sigma)
}

likelihood_cpp <- function(mdObj, x, theta) {
    .Call(`_dirichletprocess_likelihood_cpp`, mdObj, x, theta)
}

likelihood_normal_cpp <- function(mdObj, x, theta) {
    .Call(`_dirichletprocess_likelihood_normal_cpp`, mdObj, x, theta)
}

