# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

current_memory_usage <- function() {
    .Call(`_dirichletprocess_current_memory_usage`)
}

benchmark_cpp_components_impl <- function(dpObj, components, times) {
    .Call(`_dirichletprocess_benchmark_cpp_components_impl`, dpObj, components, times)
}

benchmark_cpp_components <- function(dpObj, components, times) {
    .Call(`_dirichletprocess_benchmark_cpp_components`, dpObj, components, times)
}

get_memory_tracking <- function() {
    .Call(`_dirichletprocess_get_memory_tracking`)
}

clear_memory_tracking <- function() {
    invisible(.Call(`_dirichletprocess_clear_memory_tracking`))
}

normal_likelihood_cpp <- function(x, mu, sigma) {
    .Call(`_dirichletprocess_normal_likelihood_cpp`, x, mu, sigma)
}

likelihood_cpp <- function(mdObj, x, theta) {
    .Call(`_dirichletprocess_likelihood_cpp`, mdObj, x, theta)
}

mvnormal_likelihood_cpp <- function(x, mu, sigma) {
    .Call(`_dirichletprocess_mvnormal_likelihood_cpp`, x, mu, sigma)
}

likelihood_normal_cpp <- function(mdObj, x, theta) {
    .Call(`_dirichletprocess_likelihood_normal_cpp`, mdObj, x, theta)
}

